"""Probe the recovered NA character against its authored cameras read-only.

The large NA scene is loaded once.  Each requested cut is evaluated under its
authored take, then the replacement body/face meshes, the existing hand
reference objects, and the requested camera are measured in world and camera
space.  No document is saved and no hair object is changed.
"""

from __future__ import annotations

import argparse
import json
import os
from pathlib import Path

import c4d

from c4dpy_camera_proof import (
    LEGACY_RS_CAMERA_OBJECT_ID,
    find_camera,
    find_take,
    object_path,
    walk_objects,
)


SAMPLES = (
    {
        "sourceId": "CUT-050",
        "frame": 632,
        "take": "TrackPlace",
        "cameraName": "put down",
        "cameraPath": "CAM/put down",
    },
    {
        "sourceId": "CUT-051",
        "frame": 842,
        "take": "OrbitSpin",
        "cameraName": "OrbitSpin",
        "cameraPath": "Group/OrbitSpin",
    },
    {
        "sourceId": "CUT-052",
        "frame": 918,
        "take": "RoofBreakInside",
        "cameraName": "RoofBreakInside890-1066",
        "cameraPath": "RoofBreakInside890-1066",
    },
    {
        "sourceId": "CUT-053",
        "frame": 926,
        "take": "OrbitSpin",
        "cameraName": "OrbitSpin",
        "cameraPath": "Group/OrbitSpin",
    },
    {
        "sourceId": "CUT-054",
        "frame": 1026,
        "take": "RoofBreakInside",
        "cameraName": "RoofBreakInside890-1066",
        "cameraPath": "RoofBreakInside890-1066",
    },
    {
        "sourceId": "CUT-055",
        "frame": 968,
        "take": "LayDownRoof",
        "cameraName": "LayDownRoof",
        "cameraPath": "Group/LayDownRoof",
    },
)

GEOMETRY_NAMES = (
    "SKM_AbbyV2Character_BodyMesh",
    "SKM_NewMetaHumanCharacter_FaceMesh",
)

HAND_NAMES = (
    "hand_l_2 (Copy)",
    "hand_r_2 (Copy)",
)


def vector(value: c4d.Vector) -> dict[str, float]:
    return {"x": value.x, "y": value.y, "z": value.z}


def matrix(value: c4d.Matrix) -> dict[str, dict[str, float]]:
    return {
        "off": vector(value.off),
        "v1": vector(value.v1),
        "v2": vector(value.v2),
        "v3": vector(value.v3),
    }


def branch_objects(root):
    yield root
    child = root.GetDown()
    while child:
        yield from branch_objects(child)
        child = child.GetNext()


def evaluated_point_objects(op):
    """Yield point geometry generated by *op* without crossing scene siblings."""

    source = op.GetDeformCache() or op.GetCache()
    if source is None:
        source = op
    for item in branch_objects(source):
        if isinstance(item, c4d.PointObject) and item.GetPointCount():
            yield item


def world_and_camera_bounds(op, camera):
    camera_inverse = ~camera.GetMg()
    low_world = [float("inf")] * 3
    high_world = [float("-inf")] * 3
    low_camera = [float("inf")] * 3
    high_camera = [float("-inf")] * 3
    point_count = 0
    polygon_count = 0
    geometry_paths = []
    for geometry in evaluated_point_objects(op):
        geometry_paths.append(object_path(geometry))
        point_count += geometry.GetPointCount()
        if isinstance(geometry, c4d.PolygonObject):
            polygon_count += geometry.GetPolygonCount()
        geometry_matrix = geometry.GetMg()
        for point in geometry.GetAllPoints():
            world = geometry_matrix * point
            local = camera_inverse * world
            for index, value in enumerate((world.x, world.y, world.z)):
                low_world[index] = min(low_world[index], value)
                high_world[index] = max(high_world[index], value)
            for index, value in enumerate((local.x, local.y, local.z)):
                low_camera[index] = min(low_camera[index], value)
                high_camera[index] = max(high_camera[index], value)
    if not point_count:
        return None

    def bounds_payload(low, high):
        return {
            "min": {"x": low[0], "y": low[1], "z": low[2]},
            "max": {"x": high[0], "y": high[1], "z": high[2]},
            "center": {
                "x": (low[0] + high[0]) * 0.5,
                "y": (low[1] + high[1]) * 0.5,
                "z": (low[2] + high[2]) * 0.5,
            },
            "extent": {
                "x": high[0] - low[0],
                "y": high[1] - low[1],
                "z": high[2] - low[2],
            },
        }

    return {
        "pointCount": point_count,
        "polygonCount": polygon_count,
        "evaluatedGeometryPaths": geometry_paths,
        "worldBounds": bounds_payload(low_world, high_world),
        "cameraSpaceBounds": bounds_payload(low_camera, high_camera),
    }


def effective_render_enabled(op) -> bool:
    current = op
    while current:
        if current.GetRenderMode() == c4d.MODE_OFF:
            return False
        current = current.GetUp()
    return True


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--project", type=Path, required=True)
    parser.add_argument("--output", type=Path)
    args = parser.parse_args()

    project = args.project.expanduser().resolve()
    output = args.output.expanduser().resolve() if args.output else None
    flags = (
        c4d.SCENEFILTER_OBJECTS
        | c4d.SCENEFILTER_MATERIALS
        | c4d.SCENEFILTER_DONTCORRECTOUTPUTFORMAT
    )
    doc = c4d.documents.LoadDocument(str(project), flags)
    if doc is None:
        raise RuntimeError(f"Could not load {project}")

    report = {
        "schemaVersion": 1,
        "project": str(project),
        "hairTouched": False,
        "samples": [],
    }
    try:
        c4d.documents.SetActiveDocument(doc)
        fps = doc.GetFps()
        report["fps"] = fps
        take_data = doc.GetTakeData()

        for sample in SAMPLES:
            take = find_take(take_data, sample["take"])
            if take_data and take:
                take_data.SetCurrentTake(take)
            doc.SetTime(c4d.BaseTime(sample["frame"], fps))
            doc.ExecutePasses(
                None,
                True,
                True,
                True,
                getattr(c4d, "BUILDFLAGS_NONE", 0),
            )
            camera = find_camera(
                doc, sample["cameraName"], sample["cameraPath"]
            )
            if camera is None:
                raise RuntimeError(
                    f"{sample['sourceId']}: camera missing "
                    f"{sample['cameraPath']}"
                )

            objects = list(walk_objects(doc.GetFirstObject()))
            geometry_records = []
            for name in GEOMETRY_NAMES:
                matches = [item for item in objects if item.GetName() == name]
                for item in matches:
                    geometry_records.append(
                        {
                            "name": name,
                            "path": object_path(item),
                            "renderEnabled": effective_render_enabled(item),
                            "bounds": world_and_camera_bounds(item, camera),
                        }
                    )
            hand_records = []
            camera_inverse = ~camera.GetMg()
            for name in HAND_NAMES:
                for item in objects:
                    if item.GetName() != name:
                        continue
                    world = item.GetMg().off
                    hand_records.append(
                        {
                            "name": name,
                            "path": object_path(item),
                            "world": vector(world),
                            "cameraSpace": vector(camera_inverse * world),
                            "renderEnabled": effective_render_enabled(item),
                        }
                    )
            report["samples"].append(
                {
                    **sample,
                    "evaluatedTake": take.GetName() if take else None,
                    "camera": {
                        "name": camera.GetName(),
                        "path": object_path(camera),
                        "typeId": camera.GetType(),
                        "legacyRedshift": (
                            camera.GetType() == LEGACY_RS_CAMERA_OBJECT_ID
                        ),
                        "matrix": matrix(camera.GetMg()),
                    },
                    "geometry": geometry_records,
                    "handReferences": hand_records,
                }
            )

        payload = json.dumps(report, indent=2)
        if output:
            output.parent.mkdir(parents=True, exist_ok=True)
            output.write_text(payload + "\n", encoding="utf-8")
        print(
            "PARACOSM_NA_MULTIFRAME_GEOMETRY_PROBE_JSON="
            + json.dumps(report, separators=(",", ":")),
            flush=True,
        )
    except Exception as error:
        report["error"] = f"{type(error).__name__}: {error}"
        print(
            "PARACOSM_NA_MULTIFRAME_GEOMETRY_PROBE_JSON="
            + json.dumps(report, separators=(",", ":")),
            flush=True,
        )
    finally:
        c4d.documents.KillDocument(doc)
        os._exit(0)


if __name__ == "__main__":
    main()
